# Generated by Django 5.2 on 2025-05-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
