# Generated by Django 5.2 on 2025-05-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeModel',
            new_name='Resume',
        ),
    ]
