# Generated by Django 5.2 on 2025-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='certificate',
            field=models.FileField(null=True, upload_to='certificate/'),
        ),
    ]
